language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "cornercoding-github"
    token:
      secure: "13a830902b4c1d9f13b178cc1392cdaf2e89e5e8"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
